package com.example.mangainfo

object ReviewData {
    private val NamaReviewer = arrayOf("CottonCandyLover","VK11","TheCriticsClub","qrdel","Kaiskov","JiroUmezu","Tumerking",
        "keragamming","Sapphire","riflow","Seryene299","Jest","Kiriska","Xinil","Archaeon","Polyphemus","harshtruth","Dream95",
        "Asfaria","milkpunk","tuqui","Bantamz","CP-0","Sekaiou","Cryptic-Senpai","Meowsorz","Ri-chan","jazmin_s",
        "holdenn","Amygirl90")

    private val isiReview = arrayOf("Frequently categorized with both Bleach and Naruto as one of the Shonen Big Three, One Piece is a romantic tale of pirates, treasures ...talking reindeer, panties, flying skeletons, Takoyaki selling Octopuses, and oceans roaming with Sea Monsters the size of which can take down fleets of ships. Crazy enough for you? This is the world of One Piece.\n" +
            "\n" +
            "Being categorized with Bleach and Naruto, on the surface this might strike an unfamiliar reader as another generic uncreative Shonen series; but truthfully, comparing One Piece to Bleach and Naruto would be like comparing Disney World to an elementary school playground. If these three series are the big three, then One Piece would be the boss sitting on a lavish chair smoking a cigarette, while Bleach and Naruto would be the two henchmen standing side by side of the boss and nodding at everything he says. \n"
    +"Overall:\n" +
            "\n" +
            "One Piece is my favorite manga. Period. The story is such a grand and epic adventure, with each arc topping the previous; the characters are so tear-inducingly hilarious, and the art is so cinematic and exciting, One Piece is without the doubt, the greatest Shonen manga I've ever had the pleasure of reading, and I doubt it will be topped anytime soon, if ever, as my favorite manga series. Cheers to Oda for creating this Shonen masterpiece, and may he continue to keep on going, One Piece is a manga that I love and hope to read for many many many years to come.\n" +
            "\n" +
            "Yohohoho a pirate's life for me~ ",
        "The key of success for many shounen anime is usually how well the anime is adapted from the manga. So when people are disappointed with the results of the anime, they usually resort to simply just reading the manga and follow the storyline through that. One Piece is a result of one of the few rare cases out there where the anime adaptation has followed the manga almost tooth and nail, with pretty much nothing lost within the translation between the two. With the anime receiving high review results here on MAL, I decided to take a closer look at the manga, and as far as shounen stories go, see if One Piece lives up to the accepted truth that the manga is better than the anime. This is not going to be your standard review. Because of the popularity of One Piece, where most fans know what it is already about, I will delve into more of the concepts, ideals and symbolism that sets apart One Piece from its counterparts.\n"
                +"\nIf anything, I urge you to read up to there and a little further so you can get a sense of what's to come. If you still can't understand why its so epic, its safe to say you may drop the series. However, when you compare One Piece to other shounen anime of its kind, and really, all anime and manga to date, there is no other story out there as epic, as emotional, as developing, as truly amazing as what Oda is telling in One Piece. ",
        "OVERALL - 9.69\n" +
                "\n" +
                "\n" +
                "This review is the final result of a review team composed of members from the &quot;Critics and Connoisseurs&quot; club. The team members were:\n" +
                "\n" +
                "8GaugeBrett - Who wrote the Art section and combined the individual review parts together into a whole.\n" +
                "Amaity - Who wrote the Enjoyment section.\n" +
                "Baman - Who wrote the Character section.\n" +
                "Ianmessku - Who wrote the Story section.\n" +
                "\n" +
                "Here are their individual scorings for the Manga:\n" +
                "Category - 8GaugeBrett, Amaity, Baman, Ianmessku\n" +
                "\n" +
                "Story - 9, 10, 9, 9.5\n" +
                "Art - 10, 9, 10, 9.5\n" +
                "Character - 9, 9 , 10, 10\n" +
                "Enjoyment - 10, 10, 10, 10\n" +
                "Overall - 10, 9, 10, 9.75\n" +
                "\n" +
                "In the club wide poll held for Berserk it received an average overall rating of 9.53 ",
        "\"Have you ever hated someone so much, that this feeling alone would drive you to do horrific and impossible to grasp things?\n" +
                "Have you ever hated someone so much, that your whole life was focused on finding that person and ripping him apart?\n" +
                "Have you ever hated someone so much, that you would forget about your humanity, purge it all just to find enough power, for one, single fraction of a moment, one chance to get your revenge...\n" +
                "\n" +
                "What would your eyes look like in that very moment...? Insane? Terrified? Passionate? Happy? Or maybe... satisfied...\n" +
                "\n" +
                "Look into his eyes, and find nothing there...\"\n" +
                "\n" +
                "When I first learned that there is something like Berserk manga, I was a bit surprised. That was some 7 years ago and little did I know about relations between anime and manga. Either way, I took my chances and downloaded several first volumes.\n" +
                "You can imagine my surprise when I noticed that the manga is a far cry from the anime which really made my day some time ago. Having struggled through the first chapters I moved on to the next volumes. You know, the anime itself is, in all its ingenuity, only a small fraction of the whole manga... As small as several volumes with some deleted scenes and a bit redone ending at that. However, by the moment I reached 'the anime plotline' in manga (which is volume 3) I got already interested in the manga itself. ",
        "I can't believe this... I really can't believe this...\n" +
                "\n" +
                "Naruto is a manga that has been running for 15 years, I still remember catching up with the first seasons of the anime back when I was 12, I remember skipping the dreadful filler second half from the original series and going straight to Shippuuden, I remember ALL of it and it is suddenly over. Wow... feels like an entire era ending.\n"
    +"Another thing I have to point out is that the story simply couldn't keep one consistent bad guy. The timeskip arrives and we are left with Sasuke running away to eventually become a bad guy, a psychotic ninja that wants to achieve immortality and a secret society dedicated to capturing the Tailed Beasts such as Naruto's Nine-Tailed Fox. Wanna guess which one was the real big baddie? NONE OF THEM! Sasuke? He becomes a good guy after a while. Orochimaru? Same thing. Pain, the leader of Akatsuki? Turns out he was a puppet after all. Tobi, the guy behind him? Same thing, a puppet as well. Madara? Not this one either. Black Zetsu, the guy that never had any spotlight? Nope, also a puppet! As it turns out (And here comes a big spoiler), the real big bad just so happened to be the entity that created the energy force they use in their battles? How, because she was somehow resurrected...\n" +
                "\n" +
                "Overall, Naruto is a manga that does a fair job on the first part, but completely blows it near the end. If you wanna know if it's worth reading? Not really, unless you are planning to stop just before the timeskip begins ",
        "It's hard writing this review straight after finishing the manga but I wanted to do it when It's all fresh in my mind. Naruto is a story manga and anime fans over the world know, hate or love, It is easily the most detested manga of all time but yet one of the most popular. The story is about a young boy called Naruto Uzumaki, with his entire village despising and fearing him he is practically alone in the village and because of that he as a character values friendship more than the comman man and that leads to him going above and beyond to bring his best friend Sasuke back. With many arcs and a monumental timeskip Naruto is a long story and not for people who don't have any patience, the land of waves arc, the chunin exams arc, the invasion of konoha arc, the search for tsunade arc and the sasuke retrieval arc comprised was part 1 and the flow of the arcs was great, it had practically no slow points and the emotion is high.\n" +
                "\n" +
                "With the land of the waves being the arc that fans usually remember as the arc that hooked them to Naruto with the crazy techiques and really showed of what a ninja is. The chunin exams is a favorite to many and is my favorite arc with crazy battles and learning about many tragic past to characters it is easily the arc that develops more characters than any. The Invasion of konoha arc is something that could of waited till a certain part in the story was concluded but as it was it was an amazing part in the manga and it did bring tears and epic fighting, still could of been handled differently. The search for Tsunade arc is simply the calm before the storm arc, Naruto gets training from Jiraiya and learns the infamous Rasengan while looking for the next Hokage, the dynamics between Naruto, Jiraiya and Tsunade is very well done and the ending of the arc is a pinnacle point in the series. The final arc of part 1 is outstanding to say the least, the battles in this arc are probably the biggest in part 1 and in the series and the final fight is full of emotion which Kishi is well at, overall the arc changed the story but opened up the story for different possibilities."
        ,"I was unsure if I would ever find another manga good enough to deserve my reviewing. And after reading volume six of Shingeki no Kyojin I can safely say the wait is over. What a manga!\n"
                +"OVERALL: 9/10\n" +
                "I can't give a perfect score to a manga with so few chapters so early in it's life span. But trust me; if the same amount of enjoyment I've experience in the first six volumes continues throughout the rest of the series it would be a 10 no doubt.\n" +
                "\n" +
                "You've gotta give this manga a shot. It's doing things that haven't really been done before, or at least not to this level. I'm setting the standard right now: You can't call yourself a fan of manga without reading Shingeki no Kyojin. Now get reading!\n" +
                "\n" +
                "*This review made possible by AironicallyHuman, who recommended this manga to me "
        ,"Now before you give this review a not helpful vote because of the 10/10 score. At least read what I have to say before doing your deed. I'm more interested that you guys read my review than anything else. Now let's begin!\n"
            +"Overall: 10/10. As I said before, if you want full enjoyment for this series. Re read it. If you are caught up and you're lost on the plot or you just feel you're forgetting things. Just reread it, pay attention and analyze everything. When you reread this series you will notice a lot of things you didn't notice the first time. Its also funny when you're rereading the manga and you know all the traitors in the series. You will also see how suspicious they were. Anyways time to wrap things up. Don't breeze through the chapters when reading it, take your time and enjoy the series for what it's. Whoever that has made it this far, thnx for reading! And I hope you have a wonderful day. "
        ,"Like a flutter of a butterfly’s wing, Kubo has created the dynamic of a life after death scenario, twisting people’s minds and imaginations throughout its journey with surprises, questions, and a bold statement of what happens after we leave this world. Invisible forces play into the scenes, grasping a hold of reality and raining out a massive event that not even humans can comprehend. Sparks fly as metal swords clash. Tears fall down pale cheeks. Romances bloom like a soft flower petal in the spring. People think there is nothing after life, but they are wrong. Death is only the beginning.\n"
        +"Bleach is an epic journey. Filled with action, suspense and several possible romances, it a roller coaster ride of emotions and amazing fights. Nothing compares to this manga.\n" +
                "\n" +
                "Nothing.\n" +
                "\n" +
                "I give this manga 50% on the soul cleansing scale. "
        ,"Bleach started out as a very promising character-driven manga with several great arcs. It’s a massive shame it didn’t keep up. The story starts with a bang, builds and builds, wraps up the first few arcs in a satisfying manner and then trips over itself, rolls down a hill, into the ocean and sinks into the abyss. I can say I was thoroughly disappointed with the way it ended after the potential it showed at first.\n" +
                "\n" +
                "I've been reading this manga since I was 13. The story was never really anything special, but it was fun. Initially, the characters were interesting and dynamic, they felt important and the threats felt like something they needed to overcome, to grow and to protect each other and their family. I loved seeing the way everything was depicted - supernatural or not - and the absolute creativity of some of the designs hypnotized me."
                +"\n"+
                "In summary, Bleach started its run as a pleasant experience with more ambition than it knew what to do with, and it eventually caved in under the weight of its enormous but underdeveloped cast, disproportionate focus on a single character whose importance was poorly justified with increasingly contrived plot twists, and an overabundance of questionable creative decisions."
        ,"At first this manga might not have the most original concept or story. However, the way in which it is executed is excellent. There are no such things as 'black and white' in this manga.\n" +
                "\n" +
                "Each important character has proper development and significance to the story, and none of them are there just for the sake of them being there, nor are they useless. The characters have realistic personalities, and none of them are just 'good' or 'bad'. Each character is well developed and continue to develop and none of them are completely innocent just like how it is in real life.\n" +
                "\n" +
                "I appreciated the fact that the characters are like this and this manga understands this perfectly. Characters that may seem shallow at first actually have depth to them.\n" +
                "\n" +
                "Ken Kaneki is by far one of the best developed characters I have had the pleasure of seeing. He is not just the 'nerd' or the 'cool emo badass'. Just like any person in real life, he does have secrets he wants to keep buried and not willing to accept. He has various stages of development that actually makes sense in the situations he is in. His motives and thought process is excellently displayed.\n" +
                "\n" +
                "Another good thing is how the manga does not just spoonfeed you the facts. They are foreshadowed with various references to numbers, tarot cards, symbolism and metaphors, but unless you pay attention to what you read you will not notice them and not be able to appreciate the manga in its full glory. I would recommend not just reading the manga just once but at least several times to get what you may have missed.\n" +
                "\n" +
                "Overall an amazing manga, and the cliffhanger ending was actually the best way to end the first part. "
        ,"Despite the manga's popularity, it wasn't until the anime aired this year that Tokyo Ghoul exploded in sales and became one of the top five best-selling manga in Japan (beating Kuroko's Basketball, Naruto and Magi).\n" +
                "\n" +
                "So what is it about this series that attracted such popularity? It’s by no means a perfect series, that's for sure; but it gets a lot of things right.\n" +
                "\n" +
                "The story begins by introducing readers to the timid protagonist; Kaneki Ken. Kaneki is an average college student that is forced to come to terms with living as a ghoul after a freak accident results in a ghoul's organs being transplanted into his body. Whilst not exactly the most subtle premise, the manga wisely focuses on the duality of Kaneki's life, as he attempts to maintain his normal, human life whilst having to deal with the problems that his ghoul identity incorporates into his lifestyle. The author attempts to question the morality of the world he has created, and encourages the reader to do so as well. As ghouls are required to consume human meat to survive, Kaneki is forced to confront the prospect that he may have to kill humans if he wishes to live. Usually I prefer to avoid elaborating on the story so much, but the moral dilemmas that this manga presents are one of the most interesting aspects of the series, and are one of the driving forces that keep readers engaged in the events that unfold. Unfortunately they tend to lose their significance as the story progresses, and around halfway through the series is an event that drastically alters the story and feels far too ham-fisted compared to the rest of the series, but I'll elaborate on that in the character paragraph. Added to that, the story also ends on a highly unsatisfying note. Regardless of what information is revealed in the sequel manga, this is a review of the 144 chapters that the story spans across, so any information provided externally means naught. As I read the final few chapters, my faith in the series having a gratifying conclusion eroded further and further. As the manga ends, readers are left with the story tying itself together within the last few chapters. Having to process what had happened was jarring when the series had handled its pacing so well throughout the rest of the story, and the author definitely should have reconsidered how he chose to conclude it. With the amount of literary influence in the story, it felt as though the mangaka was trying to structure his story as a classic tale of tragedy, and if that were his intention then it was well-done indeed. "
                +"\n"+
                "This manga is great, and those interested in a dark, strong story would do well to give the series a try. If some of the characters were developed more subtly, and the ending hadn't raised more questions than it answered, then this manga would definitely be bordering masterpiece territory. As it stands, Tokyo Ghoul is an undoubtedly solid manga that deserves your time."
        ,"'m glad I waited until this series was finished before I started. Considering I finished all 108 chapters in less than twenty-four hours, I'm not sure how I would have survived if I'd started earlier.\n" +
                "\n" +
                "STORY - Morals and ethics are serious business, and it isn't often that they're addressed so directly in a series. The lines that people draw vary greatly from individual to individual, and the last thing any writer wants is to severely offend any portion of its potential readership. I found it incredibly impressive then, that Death Note could so effectively address such a controversial issue -- capital punishment -- without alienating anyone in the audience. Wrapped up and packaged with some rather generic supernatural elements, Death Note may not seem like anything particularly special at first glance, but the eerie realism in the rest of the world begs the question, &quot;What would you have done?&quot; And I find that connection one of this story's greatest strengths."
                +"\n"+
                "OVERALL - Death Note has probably impressed me more than any other manga I've read (which isn't any incredible number, but still). Its degree of sophistication in all categories, story, characters, and artwork, is incredible. The story is significant; the characters are engaging; the artwork is beautiful. It's like hitting the jackpot, and I really feel like this is one of those titles that almost anyone can enjoy; better yet, I feel like this is one of those titles that can act as a gateway for the not-yet-a-manga-fan, encouraging them to explore the media further. Yeah, there's a lot of hype around Death Note, and they're definitely milking it for what it's worth (an anime, three live action movies, video games, and several spin-offs, all in the course of what, two or three years?), but for once, I think this series deserves every bit of attention it gets. Don't take the numbers on this review too lightly. I don't give 10's that often."
        ,"Alright, first let me say that, the manga is infinitely better than the anime. INFINITELY. But, with that being said, I believe the manga should have ended at chapter 58/59. After that, it's just a crapload of \"yeah-right\" and \"ooookay\" and \"bullshit\". Seriously, I hated the second half of the story. However, the first half was so ridiculously good, that I just couldn't give the manga a bad score.\n" +
                "\n" +
                "With that being said, on to the details.\n" +
                "\n" +
                "Story\n" +
                "Brilliant. I can't think of anything else that has even come close to something like this. Entertaining, smart, and keeps you on the edge of your seat. You'll want to read the chapter after chapter to find out what happens next.\n" +
                "\n" +
                "Art\n" +
                "Looks good to me. Figures are drawn well and the females were good looking.\n" +
                "\n" +
                "Character\n" +
                "By far, the best part of this show. The characters were...alive. You felt like you really \"knew\" the people. Almost like reading a book there was so much detail. There aren't any that follow a typical \"stupid\" or \"cliche\" trademark either. Thank god.\n" +
                "\n" +
                "Enjoyment\n" +
                "Well, as I said, I didn't enjoy the second half of the story. After the first half, my enjoyment level plummeted. Read the second half, if only just to say you have.\n" +
                "\n" +
                "Overall\n" +
                "Do yourself a favor and stop after chapter 57-59. You'll enjoy the manga a lot more and probably be happy with a well thought out ending (as opposed to the chapter 108 thrown together ending). "
        ,"One of the problems with something being truly good is that every so often it becomes a victim of its own success, and in a sense that's what happened with the fans of Full Metal Alchemist.\n" +
                "\n" +
                "Arakawa Hiromu's tale of two brothers and their adventures in alchemy is one of the most well known stories in anime and manga to date, and has spawned a horde of games, a movie (with a second one planned), numerous doujins and fanfics, piles of merchandise ranging from tatoos to chibi plushies, and two very different anime series. The story itself is very typically shounen at times, however there is a depth to proceedings that belies the initial look and feel of the manga. While things begin innocuously enough, it's not long before the reader finds themselves wrestling with moral, religious, and even philosophical motives and actions as the Elric brothers make their journey towards their destiny."
                +"\n"+
                "It's pretty obvious that I enjoyed Full Metal Alchemist immensely, however my only real gripe with the manga, especially after reading Arakawa's other works, is that there are too many occasions where it feels like the author has purposely moved away from a theme or situation that was used in the original anime, and this can make parts of the story feel a bit rushed. That said, this is actually a minor problem as the whole tale fits together extremely well, and in terms of content Full Metal Alchemist is easily on par with Takahashi Rumiko's masterpiece.\n" +
                "\n" +
                "What Arakawa Hiromu has given us is a work that is truly good, despite some minor niggles here and there, and while there are some typically shounen aspects to the tale, Full Metal Alchemist, like Inuaysha, is a far cry from what one would consider a typical shounen manga.\n" +
                "\n" +
                "Isn't it ironic then, that the two of greatest shounen tales weren't written by men? "
        ,"Fullmetal Alchemist is not spectacular. What I mean is that nothing about the art or the plot immediately strikes the audience as impressive or unique. The art is not flashy or detailed. It gets the job done, but only just. The action is easy to follow from panel to panel, and it is just dynamic enough to be interesting. The characters are all pretty much distinguishable from each other, despite their simple designs, and some of them look kinda cool. More than anything, the art is solid. It never gets in the way of the audience's enjoyment. And sometimes that's enough. The only times I ever took issue with the style were when the characters were morphed into chibis in a weak attempt at comedy.\n" +
                "\n" +
                "And that brings me to my next point: The comedy. It's not comedic. Early on, there are many repetitive running gags and the only thing they accomplish is kicking me out of the story. Such a blatant attempt to appeal to the audience can backfire if delivered poorly, and so it felt like a slap in the face delivered through the 4th wall. I don't want to deal with that. But I think that the mangaka realized this direction wasn't working early on, and the manga generally gets more serious as time passes.\n"
                +"More than anything, Fullmetal Alchemist is solid. Most of its imperfections are minor and don't reach the series' core. Nothing about the series is all that exceptional or original in itself, but it adds up into a very well-structured and cohesive work that manages to avoid making a lot of mistakes that are not often avoided. (And, despite its popularity, it never overstayed its welcome and was relatively concise for what it was.) Still, it doesn't really accomplish all that much that I haven't seen done as well or better. It is simply less flawed than most similar works. This makes it feel unique holistically, but not on a more critical examination. It is unique in that you'd be hard-pressed to find a more perfect battle shounen, but this quality is negatively defined: Fullmetal Alchemist is most praise worthy for the things it does not do; what it does do is not nearly as impressive or difficult.\n" +
                "\n" +
                "The lack of originality or risk-taking factors against Fullmetal Alchemist, but the form and presentation of it warrants a solid 7. It's quite good, but not quite great."
        ,"Oh Fairy Tail, You could have been good, you had so, so much potential in you, but here you are, going out with barely a yelp.\n" +
                "\n" +
                "Where did it go wrong Hiro? You had an immensly popular manga at your disposal to really give all your readers a satisfying manga to reread over and over again. You had the chance to make Fairy Tail something really, really great . But you wasted the opportunity. You have thrown it away by being stubborn to the end.\n" +
                "\n" +
                "Of course, I'm not saying this out of no reason. There are a lot of good reasons as to why many readers, including me, were sooooo disappointed at how the manga turned out. However, there is one main reason that has been the biggest downfall to Fairy Tail, and that is the formula.\n" +
                "\n" +
                "You see, Fairy Tail only ever has the same formula for every single one of its arcs. Meet Enemy, Fight, Get beaten up, .... activate Friendship power and win. That's it. That is the one and ONLY formula Hiro relies on to create each and every arcs. It's so ridiculous to the point that, in the later arcs, everyone could predict the outcome of the fight so easily. \"Fairy Tail will win, Fairy Tail will not lose a single member because Natsu and co. will activate their bullshit asspull to overcome the enemy every single fight.\" This asspull was somehow most present in the damn FINAL ARC. Meet strong enemies, Fight but get pushed back a bit, then a random speech about family, friends, guild... then win. It's unbelievable how the \"hyped\" fights were all ended this way. This, this right here is what truly killed Fairy Tail."
                +"\n"+
                "That's it really. I was going to give this a higher score had the Final arc been as good as the Tartarus arc, but it was an epic failure, one of the worst in the series. I don't really recommend this series to anyone anymore, especially after the travesty that was the Final Arc. So please, if you want to save some time by not reading through something that will infuriate and disappoint you, please step away.\n" +
                "Actually, just go onto youtube and find the music scores for Fairy Tail. The music score is undeniably great, and most of them are worth listening to at least once. Which makes it even more shame as it was wasted on this.\n" +
                "\n" +
                "Good job Hiro Mashima. Good job on throwing away a potentially great manga. "
        ," wise man once said...\"To deny Fairy Tail as absolute garbage, is to deny reality itself\"\n" +
                "\n" +
                "At the risk of this turning into a rant, I will be censoring myself a lot to give a genuine review. This review will contain very minor spoilers as names (except the main character slot) will be withheld because for god know what reason you still want to pick up this manga after everything I said, you won't be spoiled...you have been warned.\n" +
                "\n" +
                "Well, well, well...what can I say that hasn't been said about FT? Actually nothing really. FT is what happens when you wrote 1/4 of your manga and then fire all your co-writing staff, go to a nursery and replace good plot with whatever those toddlers vomit on a page and there you have what FT is. Granted for a battle shounen, you shouldn't expect much when it comes story and characters but this just happens to be worse than every battle shounen I've ever watched/read. How did it fall so fast into the shitter that it actually becomes a chore to read it every week? I remember back in the day when a new chapter would come out and I would genuinely feel excited but as time progressed and the quality of work just became worse and worse, you get the feeling of apathy because your hopes and expectations have been shattered time and time again. At least I can praise FT for one thing and that is its unpredictability because it surprises you every time in how much worse it can become with every chapter."
                +"\n"+
                "The characters don't even look that much different especially the female characters. It's like Hiro just took the same body shape for every female except for Wendy that is treated as a loli for comedic scenes about her big breast envy and a bit of fan-service for those that want that...just horriible and lazy.\n" +
                "\n" +
                "The story is a linear set of events that really serve no purpose other than introducing fodder villains for Fairy Tail to bulldoze and the final arc has to be one of the worst things in digital and printed history. Even the final chapter like seriously? You couldn't give the fans a better ending than that after suffering through that mess? I wouldn't print it on toilet paper. Over 500 chapters and 11 years of work, most of it is horrible but I guess the series had to remain true to itself and remain trash to the end...wouldn't want to mess with the Krabby Patty formula now do we?\n" +
                "\n" +
                "Personally I've spent 4 years following this series and it was one of the worse things I've read and now I've have nothing more to say except goodbye and good riddance. "
        ,"Oyasumi Punpun is the best example I have ever found of something which you should not judge by its literal cover. Looking at the picture on MAL, I initially thought the story was about some young girl and a weird penguin/bird thing and only really added it to my list because it’s ranked #15 on this site. It was not until after I read another manga by the author, Asano Inio, called Nijigahara Holograph, and looked more into what this manga was actually about, that I finally decided to read it. And I could not have been more wrong in my initial assumption. But enough about that intro which was just to help dispel any similar thoughts people looking at this manga might have, I’ll get into the real review now.\n" +
                "\n" +
                "So many manga (and actually many things in about every single story-telling medium that humans have ever had) often try to create likeable characters, a plot that while it may have many sad parts manages to rebound and become upbeat at some points, and/or very unrealistic characters or settings. Oyasumi Punpun is basically the opposite of all of that."
                +"\n"+
                " Throughout the manga, Punpun goes through different drama and relationships, problems and anxieties, and different designs. The characters he meets (especially the girls he is close to) change each time. The story often focuses on characters other than Punpun in order to piece together the entire story. I won’t talk about all them as it would take too long, but if you want to see all of the characters who are very important at some point, just go to the character list.\n" +
                "\n" +
                "This is now one of my favorite manga and only the second that I have given a 10/10 rating to. It’s a masterpiece that shows how real life works and how all of the problems in real life are not easily solvable like they are in many stories. It may be one of the most depressing manga out there, but if you can handle that kind of story as well as many mature themes and some nudity, then I highly recommend Oyasumi Punpun. It’s not something you should go into lightly, but if you enjoy these kind of life-changing stories, then this is something you should not miss. "
        ,"I really hated Punpun. No, not the manga. The character. I'll get to this in a minute.\n" +
                "\n" +
                "I was reluctantly dragged into reading this bizarre tale during its brief boom in popularity. Its ensemble of morally repugnant but nonetheless interesting characters even sort of drove me away at first. The story is not for the faint of heart. The early story deals with themes like domestic abuse, suicide, rape, divorce, and violence to name a few. The minute you start liking a character, they screw up. And you /can't/ like them.\n" +
                "\n" +
                "And I hate Punpun. Punpun is a sort of head-in-the-clouds Joe Schmo abstracted as a bird cartoon, probably the most recognizable part of the comic. And despite his violent behavior, his confusion, his flaws, by the end he was... oddly easy to relate to. He's a bird or a pyramid or a devil 20-some, he's an amoral and severely depressed Japanese Holden Caulfield. He's disillusioned with love and sex. He's fixated on hatred and death.\n" +
                "\n" +
                "But despite the bleakness and, frankly *a little too postmodern for its own good* style, I couldn't recommend it higher. Especially if, like myself, you are mentally ill. Oyasumi Punpun offers a word of comfort for the lost, for the depressed, for the failures.\n" +
                "\n" +
                "Similar titles, Welcome to the NHK, Aku No Hana, I could probably name quite a few, deal with these issues well, but are far more plot-centric. Punpun works in a sort of plotless style not unlike slice of life, except said slice is more like the whole pie.\n" +
                "\n" +
                "Oyasumi Punpun will make you feel. Bad, good, confused, I don't know. I can't say I've read another manga so powerful. Artistic brilliance. Compelling characters. There's more to personally analyze here than House of Leaves (see: striped-shirt litterbug incident, Pegasus cult, the god of poop, Punpun's personal God).\n" +
                "\n" +
                "Without spoiling anything this manga doesn't give you a feel-good message. It does, however, tell you: \"Hey, I understand you're a basket case. And you don't think you can make it. But there's more of us out here! So hang in there. Life might never be good, but sometimes everything will be okay.\" "
        ,"Onepunchman, the story of the great hero Saitama, an unemployed guy who found his career in being a superhero, after training for three years he achieved great power, sadly for him, he manages to destroy any enemy in just one punch, rending him bored and empty.\n" +
                "\n" +
                "Story: Simple and direct action manga, overpowered Hero fights enemies, but he's attitude while doing it compliments so much the comedy.\n" +
                "\n" +
                "Art: Murata Yusuke, amazing artist who worked in a lot of big names before, he's clear trace makes every page enjoyable, great detail in the images and clarity for understanding what exactly is happening in each page.\n" +
                "\n" +
                "Characters: Saitama, main character and protagonist of the story,not finding thrill in battles anymore has left him bored and simple, he lacks any reaction to any enemy/monster/destroyer of worlds, with a smile and a positive attitude he looks for a goal. Genos, sidekick, serious cyborg who thinks he found a teacher in Saitama now follows in the hope of becoming as powerful as him, the characters balance each other quite well (This's been written around chapter 18 surely others will appear later)\n" +
                "\n" +
                "Enjoyment: Personally, I have had a great time reading this manga, I look up for each new character and I'm sure a lot of people do too. It's easily inexplicable how the story feels fresh again when the characters feel almost too powerfull (Think how goku would be if he had the level at the end of DB-GT during DB)\n" +
                "\n" +
                "Overall :I will recommend this to any fan of superheroes, comedy or action. "
        ,"It's seriously the best. You are doing yourself an extreme disservice if you don't sit down and read that Onepunch greatness. The plot's plastered literally everywhere so let's just go ahead with the usual breakdown thing that seems to be the way to go on mal. Welcome to the glorious anti-stereotypical battle manga, ONEPUNCH M\n" +
                "Story-7\n" +
                "It's not gonna blow you out of the water with an extreme level of intricately detailed depth and massive psychological implications, but this is literally one of a TINY number of instances where I couldn't care less if I actually put considerable conscious effort into doing so. Story for the most part flows well and has enough bubbling (or violently exploding) away at any one time to keep me interested.\n" +
                "Art-10\n" +
                "Yeah. 10. It's just that downright astoundingly nice to look at. Character designs are interesting and extremely detailed, backgrounds are amazing and there are literally bits you can string into a gif image and have yerself a small piece of absurdly fluid (coming from a manga at least) animation. Our beloved MC here is the only one who's drawn horribly-but that's part of the joke. He generally looks like he's drawn in Microsoft paint, but when he shifts to a serious art syle you know shit is about to go DOWN. Best art I've seen in a very long time.\n" +
                "Character-10\n" +
                "This is one of those things that's probably hit or miss depending on your tastes, but I personally LOVE these characters. Saitama is our MC and super-OP badass mofo who people don't take seriously cause he's bald and walks around in tights and a cape-you'll probably grow to love him as he makes mountains out of molehills (ie:missing a convenient sale at the shops while killing bad guys) and generally not caring in the slightest about things that seemingly actually matter. There's Genos, the also extremely badass and super-attractive fangirl bait who possesses a plethora of crazy robotic arm attachments for taking care of the toughest jobs, and a host of other heroes ranging from licenceless rider, a dude on a bike who rides around fighting crime, to guys like Bang and Metal Knight, Also super-OP and awesome. Vibrant cast who grew on me faster than most.\n" +
                "Enjoyment-Gotta be 10 man, Onepunch is the biggest breath of fresh air I've had in a while as it stubbornly wages it's one-man war on shonen battle manga. If you're sick of shitty tropes and garbage plot devices, prepare to see them mocked relentlessy in a setting where the action and characters still manage to dwarf most other battle manga.\n" +
                "\n" +
                "I'm gonna go with like 9.5/10\n" +
                "This be mah jam. "
        ,"It's not everyday you make an account on a site you lurk just to post a review, but here I am.\n" +
                "\n" +
                "Over-the-top entertainment, really easy to get into, great artwork, fun and likable characters. It’s no surprise this manga series is as popular as it is. Reading the author’s note on the first volume, it’s clear the author, Kohei Horikoshi, just wanted to create something fun and enjoyable, and he succeeded in doing so, at least in my opinion.\n" +
                "\n" +
                "So why the 4? Well, you see, this review focuses on the writing in this manga series, and I'm going to be as brutally honest as I can be about it. It seems weird to do so, since this manga isn’t trying to be anything more than it is. But you often hear so much about how great the writing in this manga is compared to other shounen manga series. God knows how many times I was told this before I decided to give it a read. But the reality is quite different.\n" +
                "\n" +
                "If I could compare the story to in this manga to something similar, it would be the Pokemon series. In every Pokemon saga prior to Sun & Moon, Ash will travel to a new region, run into some girl that decides to travel with him, meet a new rival that kicks his ass in almost if not all their encounters, gather all the badges in the region and assemble a Pokemon team, enter the Pokemon League where he finally bests his rival once and for all, ultimately lose the Pokemon League, and then it's back to square one with him traveling to another new region, where he runs into some girl, and you know the rest..."
                +"\n"+
                "In conclusion, while this manga is fun to read, I would be lying if I told you the writing is anything more than just barely competent, I mean it was already contradicting itself as early as the second chapter and that's a sign for what to expect from the writing in this manga. You could call it an average shounen but I've read Bleach and that one bothered to flesh out its setting and characters a little. Almost nothing in this manga is fleshed out, it’s all surface level and incredibly bland, so contrary to what people tell you, if you’re looking for a well fleshed out story, this isn't it. "
        ,"It's the rising star of Jump, the so called \"next Naruto/One Piece.\" Yes, it's of the mold of the two. Yes, you can see the similarities in holistic structure, but what is it that makes Boku no Hero Academia a compelling read for shounen fans looking for something to pass the time?\n" +
                "\n" +
                "Story- 7\n" +
                "The premise is simple: Many people have superpowers, the boy has none, he gains powers through strange means much later than others, and he enters THE school of superpower training. Right.\n" +
                "It is only a 7 because the premise has been set and there are simply developments going on at the moment-- this manga will likely be written for a while and being 39 chapters in is kind of early for the story to develop. That being said, story isn't a strong suit CURRENTLY, but the quality of writing has been gaining steam in recent weeks (for a shounen weekly) and Horikoshi Sensei showing flashes of brilliance from time to time, I think this will be higher soon enough.\n" +
                "\n" +
                "Art- 10\n" +
                "The style is typically cartoony, but this is only because of the whole superpower premise. Sure, it isn't realistic, but if you look at the art in context, it is exceptionally well done. Horikoshi has certainly developed his own style that we could distinguish after reading Boku no Hero Academia for a few chapters. The art is detailed all around: the backgrounds, character designs, facial expressions; you name it. To top it all off, it's consistent, and really, that's all we could ask for isn't it?\n" +
                "(Note to fellow readers: I think Midoriya freak out faces and Bakugou psycho faces are insanely good)\n" +
                "\n" +
                "Character- 9\n" +
                "There are only so many characters: Izuku (main character), Bakugou (MC main rival), Todoroki (MC rival 2/upcoming close friend), Uraraka (heroine), All Might (the hero Izuku looks up to), and plenty more who are nameable, but the list would be too long.\n" +
                "The fact of the matter is that they are nameable. Readers can distinguish between these characters not only because of their different physical designs but their personalities as well. The characters who seem as though they'll be relevant in the future are being developed with their own pasts. And these character layouts are just so different from most shounen manga we've seen in the past 30 years or so.\n" +
                "For example: Izuku and Bakugou. (Minor spoilers ahead) Midoriya isn't your typical main shounen in the sense that he's an idiot who loves to eat and such, but he thinks for himself. He writes notes on people he think might be rivals with as material he could possibly get on them. He analyzes everything down to a science, fanboys about them, and anticipates how anyone could fight each other due to their specific circumstances. He overthinks, sure, but he does it beautifully and relatably that I think most of us would understand.\n" +
                "Then we have Bakugou, the rival. He is so mean: bullies people around him, taunts them, and destroys their souls. Yet, at the same time, we can see another layer under him that wants to be a hero the same way Midoriya does, just coming to conclusions in a different manner than Izuku. He also analyzes, albeit to a much lesser degree; he lets the powers he's used to do the other half of the work for him.\n" +
                "The characters really express Horikoshi's respect for Togashi: thinkers who manage to be realistic but at the same time captures our attention by being over the top at the right times, motivating us to be the best we can be. Really, characters are a strong suit here.\n" +
                "\n" +
                "Enjoyment- 10\n" +
                "I love reading this each week. I look forward to the art, the character development (there's always some), and hope for the day that the story takes a turn and just skyrockets and makes this manga THE big thing. It's just a good part of my day when I read it.\n" +
                "\n" +
                "Overall- 9\n" +
                "Some shounen veterans might say this number is too high, but I'm giving this manga a 9 due to ALL factors, especially my investment in it. Although at the moment it's an 8, I think it will become a 9 because of the direction Horikoshi is taking it each week. It has strong development, consistent art, and good writing overall. If you like shounen, you will definitely enjoy reading this: it has all of the normal stuff in blood, tears, and determination, but readers of all will definitely enjoy reading this for the character development if nothing else. "
        ,"If you were a bully, would you try to change who you were? If you were a victim of bullying, would you forgive your assailant? Koe no Katachi (literally translated “The Shape of Voice” in English) by Ooima Yoshitoki details the story of Ishida Shouya, and his growth from a savage terror in elementary school, concerned only with satisfying his own need for stimulation, to a young man with concern and empathy for those around him.\n" +
                "\n" +
                "We’re first introduced to Shouya as a child, performing a “test of courage” with his friends. You see, dear reader, Shouya is afraid of boredom. School is boring, stagnating is boring, living is boring, so he has to do something to cut through that cloud of drivel. What does he do? He jumps off of bridges. He pours salt on slugs. He eggs his two best friends on into getting into the same sort of trouble that he does. Shouya is a problem child, and this is made very clear from the very beginning of Koe no Katachi. When he meets Nishimiya Shouko, a deaf girl who transfers into his elementary school, he does not treat her like a person – he treats her like a tool to alleviate his boredom. He yells in her ear, pours dirt on her, and tosses out her hearing aids, not thinking for a moment that she is just another human being. No, she’s an alien from the planet Nishimiya, and she doesn’t understand human speech."
                +"\n"+
                "Ooima Yoshitoki is a very good artist. Koe no Katachi has stellar art for a manga published on a weekly basis, with very few inconsistencies and no deterioration in quality that I have been able to notice. Both characters and backgrounds are detailed, and each character has a distinctive design to make them stand out from the rest. Characters are actually fairly realistic looking apart from Nagatsuka. Screentones are used to their full potential and there are definitely no cuts and corners taken when it comes to the artwork.\n" +
                "\n" +
                "What can I say about Koe no Katachi, in closing? It was certainly an amazing ride and I’m glad I came along for it. While it does have its issues here and there, one must take into account that this is the debut work of a very young author. It is truly an exceptional manga with the subject matter it tackles and the quality it is written, and I wholeheartedly label it a must-read for anyone interested in literature in general. Remember, kids, no matter what mistakes you’ve committed in the past, if you regret them and see them as they are, you’re a good person. Don’t be afraid of facing your fears, because that is only the first step of the journey you’re about to take. Growing up is a painful process – but we all have to do it. And at the end, you’ll reach a door. You know what you’ll find behind that door? Your future, yours to take into your own hands, as bright as you are able to make it. You can only help yourself as long as you are alive. "
        ,"While reading this, I thought this would be the greatest thing since internet porn. You got a deaf girl who is getting bullied by some kids, you get a main character who is a bundle of development, and you get some good feels out of it. And then it ends. Abruptly like your mother slamming on the breaks suddenly without your seatbelt and you suddenly hit your head on the dashboard. Then you ask your mom \"Why the hell did you do that?\" And then she shrugs her shoulders.\n" +
                "\n" +
                "Throughout the duration of this mango, it was a rollercoaster of kids trying to not get eaten up by their past. Some force their way to overcome a self-induced obstacles haunting them. And that's about it really. The manga really just stagnated about half way through and never left that point. Nothing happened between the middle and the end before succumbing to a stop. Some characters don't get their limelight, some questions are left unanswered, and the feeling that it could have been so much more. It leaves a bad taste in the mouth. "
        ,"At first this series annoyed me to hell. Not because I'd read it, mind you. But because every time I'm go to check for some freaking updates there would be Kuroshitsuji at the top of the list, taunting me and singing \"na-na-na-na you don't read me!\". The obvious solution would be to read it but I was stubborn and the title looked like a shounen which i was not in the mood for.\n" +
                "\n" +
                "Finally I gave in and clicked the link on onemanga, which gave me the most misleading synopsis I'd ever read. It went:\n" +
                "\n" +
                "\"To what extent must a housekeeper do things to be acceptable? One of the noble families of England: Phantomhive's butler: Sebastian Michaels has got unquestionably perfect knowledge, manners, talent with materials, martial arts, et cetera: but is also able to serve a 12 year old master. Wearing a grey tailcoat, gracefully brewing the worlds strongest red tea, please read on to see how such a perfect butler copes with such a master...\" (directly copy and pasted from onemanga, btw)\n" +
                "\n" +
                "I thought \"Oh! That sounds funny! A really happy manga!\" HAHAHAHA! Yeah RIGHT! This thing ended up being one of the darkest, horrific, deep, and twisted mangas I've ever read! And I STILL loved it!\n" +
                "\n" +
                "Even though my initial idea of the manga was totally misconceived I still found enjoyment of the highest degree.\n" +
                "\n" +
                "What the story is really about is the pair, Sebastian (the perfect butler) and Ciel (the cold, calculating 12-year-old), living in the underworld of high society. Ciel is an orphan with a fortune, an eyepatch, and a deal with the demon Sebastian. In the manga we don't know the details of this deal (and you do in the anime but I don't trust animes) jut that Sebastian has to protect Ciel at all cost until a certain time at which point Sebastian gets Ciel's soul.\n" +
                "\n" +
                "Of course, this is all rather heavy for a twelve-year-old (heck, at the time they made the deal, Ciel was 10!) but Ciel never appears to waver. He is strong, smart, cold, and far from merciful.\n" +
                "At least that's what he tries to be. As the story progresses, it becomes more and more obvious that Ciel is desperate to hide all emotion so as to protect himself from the world. His experiences hardened him and much of the series seems to be about him facing his own innocence and realizing his weaknesses.\n" +
                "\n" +
                "But where Ciel is an open book, ready to read by anxious readers, Sebastian is closed off and a mystery. His constant smile and dark manor is menacing and you can't help but suspect he's only caring for Ciel for his tasty, tasty soul. But in the anime there are moments that suggest he may actually care for Ciel.\n" +
                "\n" +
                "I would like to note at his time that this series is NOT a shounen ai/yaoi. Since the two main characters are a bishi and a shouta and they have a \"unique relationship\" it is assumed they are taking part in \"inappropriate conduct\" (aka they're joining NMBLA). I think this is disgusting. I can't believe people wish to think that. Why must all wholesome reltionships be ruined by people and their filthy minds\n" +
                "\n" +
                "The relationship between these two is like a forced trust. Sebastian knows Ciel can't hurt him and Ciel knows Sebastian is bound by a sacred contract that can't be broken. Sebastian is the only person Ciel can trust unconditionally and since Sebastien is so strong he knows that if anyone even tries to cross him, they're dead. It's not love, just a partnership.Now that I'm done with that, I'd like to make note of the story. As opposed to most shoujos this series is divided into lots of mini arcs and stories which usually teach you something knew about these characters. They usually start with Ciel being told by the Queen to go do something for her. Then Ciel has to run off with Sebastian and do her bidding. These stories will usually start of with lots of funny, clever comments partnered with new characters to further the story. Then it plunges into some deep, dark plot line from whence are heroes may never return (they always do anyway).\n" +
                "\n" +
                "In a lot of ways this manga reminds me of GodChild. Very dark and set in the same period. The only difference is I actually like the art in Kuroshitsuji. The detail is through the roof with high style, delicious sweets, lovely London town, and wonderful style to boot.\n" +
                "\n" +
                "I hope you read this series and enjoy it as much as I do! ^_^ "
        ,"Story (8/10):\n" +
                "&ldquo;Aku made shitsuji desu / I am a butler to the core&rdquo;\n" +
                "\n" +
                "Kuroshitsuji takes place in Victorian era London and starts us off in the manor house of Ciel Phantomhive, the twelve year old head of the prominent noble English family. Assisting this young capitalist is Sebastian Michaelis, everyone&rsquo;s ideal butler, who wishes for nothing more than to fulfill his young master&rsquo;s every need. Now you may ask &ndash; what kind of reader am I, to be so easily marveled by an aristocrat and a merely simple butler? Well, I am obliged to highlight the fact that Sebastian is merely no ordinary butler, and as the story progresses, we soon come to realize that there is more to young Ciel and cunning Sebastian&rsquo;s relationship. This fine butler is not simply serving Ciel out of the goodness of his heart or for any wealth, but instead is bound to the Phantomhive head by a rather dark contract &ndash; all of which is gradually being unraveled as each chapter passes. The story is fantastic and although at times it may seem that some chapters were a little slow and did not create as much emphasis as the last &ndash; each is important and ultimately fun to read. Consequently, the story itself is quite unique and definitely an interesting read. Moreover, albeit it may at times seem devoid of something, it will surely not displease in making you laugh and enjoying it enthusiastically.\n" +
                "\n" +
                "Art (10/10):\n" +
                "The artwork in Kuroshitsuji is in my opinion extremely beautiful. Almost right off the top, I&rsquo;m sure you will be impressed. The backgrounds when shown are marvelous and portray an excellent image. The artwork in Kuroshitsuji is magnificent in how well it depicts the Victorian era. By this, I draw attention to the intricate clothing designs that are worn by our characters, the nineteenth century tea and china sets, as well as the interior of the Phantomhive manor. Furthermore moving onto the character designs themselves &ndash; I must conclude that they are one of the best I have seen. Sebastian&rsquo;s look floods sophistication, complexity and style; whereas upon taking a glance at Ciel&rsquo;s character you immediately recognize an air of superiority, cleverness, and class. The art I believe is one of the best aspects of this manga.\n" +
                "\n" +
                "Character (10/10):\n" +
                "The characters are a definite plus for Kuroshitsuji. Ciel Phantomhive is a twelve year old business savvy prodigy who is now the head of the noble English Phantomhive family. He prides on being a well-mannered, mature and calm young man and takes pleasure in winning, whether it be in a deal to gain material objects or to gain something of more value &ndash; hence forth proving his interest and hard to believe proficiency in playing games. Additionally, Ciel is the master of Sebastian whom he sees as his pawn and someone who is meant to endure anything in the name of Phantomhive.\n" +
                "\n" +
                "Thus bringing us to the sly yet remarkable character of Sebastian Michaelis as the butler of young master Ciel. Sebastian is without a doubt, the best butler to ever serve nobility as he shows his ability to cook as a professional chef, clean so well that he leaves not a speck of dust, maintain the garden and indubitably perform many other tasks while still finding the time to make his master some tea and cake. Sebastian&rsquo;s awesomeness is further proven as he is the first butler to be able to fight and fend off his masters&rsquo; adversaries with simple eating utensils. Yes, Sebastian is the true embodiment of perfection. However, as the story progresses &ndash; Sebastian&rsquo;s true character becomes more and more clear.\n" +
                "\n" +
                "One thing I must accurately say about the two main characters and of all the other supporting characters as well, is that each person has a unique story to tell. Although backgrounds are being revealed gradually &ndash; it&rsquo;s quite understandable each character has quite a lot to offer. What is more is that although the story is often times meant to be dark; there are many characters that are ready to provide comical relief at any moment. As stated once before, each character has quite a lot to present from their personality to the overall story.\n" +
                "\n" +
                "Enjoyment (9/10):\n" +
                "I am undeniably enjoying Kuroshitsuji to its fullest potential. Although many questions have been provoked, that is to be expected of a manga that is still publishing and continuing with high hopes. Additionally, as each chapter is being released, questions are being answered yet more questions are being put forth &ndash; therefore peaking my curiosity to a greater extent. Kuroshitsuji is a perfect balance of supernatural action, mystery and comedy that is makes an amazing manga. Furthermore &ndash; this is especially appealing to the females as it contains many &ldquo;hot bishes/shotas&rdquo; ^_^;;\n" +
                "\n" +
                "Overall (9/10):\n" +
                "All in all, I would recommend Kuroshitsuji to anyone who is interested in reading a manga with a unique and twisting plot, great characters all whom differ in their personalities and abilities and with awe-inspiring art. I am thoroughly enjoying it and I hope others will come to love it as well :)"
        ,"Story 10/10 character design 10/10 mangaka 1/10\n" +
                "\n" +
                "I've never seen a human lazy like that. Togashi sensei... Your imagination is so cool but you do not want to show us your mental abilities... Howewer he is so lazy that he got only one page of an important scene instead of a lot of pages. So paper is full of bubbles lol\n" +
                "\n" +
                "Especially i love character designs of this manga. Characters have different hair styles, different make up, different clothes, different accesorises... Each of them have great looking. HxH is a really chic manga.\n" +
                "\n" +
                "Ad i wonder Gon's mother. Togashi sensei, please show us her!!!! "
        ,"Welcome to the world of Hunter X Hunter where people pursue to become Hunters. But to become one, one must undergo the Hunter Exam. Thousands of people participate in this exam. Among them is a kid name Gon Freecs who longs to meet his father, a great hunter, but in order to do so, he must become a great Hunter and follow his footsteps. Along the way, he meets Killua, a kid whose family is famous for being assassins, Kurapika, a kind and loyal friend but at times reckless due to his revenge motive and Leorio, a brash man who aims to be a successful Hunter specializing in medical treatments.\n" +
                "\n" +
                "Yoshihiro Togashi is the same guy who wrote the 1994 hit YuYu Hakusho, a successful long running shounen. And this manga is no exception.\n" +
                "\n" +
                "Nearly all long-running shounens throughout anime history has already been labeled tedious, dull and unimaginative. Without fail, HxH will relieve you of that perspective.\n" +
                "\n" +
                "Hxh simply has it all. Action, check. Pragmatic characters, check. Psychological contest, check. It can be a psychological thriller or an action-packed manga. Either way, HxH is superbly crafted.\n" +
                "\n" +
                "The anime played out with touches of pathos and humor creating a superb atmosphere. The manga provided numerous slap-stick comedies to lighten the mood a little. But when its serious, its serious. The intensity of HxH cannot be denied.\n" +
                "\n" +
                "While it isn't groundbreaking in the concept aspect, the real treat is in the execution. Supernatural abilities aside, this manga undertakes a realistic approach. The little things actually matter from getting adapting your eyes to the dark to increasing efficiency on running, every small thing counts. This results to intense an conflict for both the mind and the muscle during battle's. HxH concentrate's on the adventure aspect more so than the fighting aspect. So dont expect any out-of-this-world &quot;sudden power outbursts&quot; to save the day because HxH wont allow it. And thats one of the many things you'll like bout this manga.\n" +
                "Regardless of this, HxH still proves to be enough to considered an action. The action does play it safe but it is still highly invigorating. It succeeds in keeping many readers on their toes, and often leaves readers with cliffhangers that are big and small.\n" +
                "\n" +
                "The rather slow paced scripts are fleshed out with a set of tremendous central and supporting characters. The various other characters and factions involved in playing the manga do not end up seeming flat. They take the time to develop and flesh out even some of incidentally encountered characters appearing only for a chapter even if it would have been easier to simply have them appear for their necessary encounters without giving us any real insight into their personality.\n" +
                "Also character developments are a plus. While Gon remains static, Killua and Kurapika in particular, goes through massive changes throughout the manga .\n" +
                "\n" +
                "To some the art is horrible. But I dont think its bad at all. I mean, it isnt amazing but is simply good. Another issue is the amount of text. Sometimes it can be overwhelming to the reader, since HxH will rain you with texts everywhere on the panel. HxH doesnt want to seem miss any explanations and leave some plot holes. It wants to be rational, as much as possible. Incredible sense of detail shows in key points of the story.\n" +
                "\n" +
                "Once you reach the Hunter Exams, everything will shift to overdrive. If that arc doesnt interest you in the slightest, I suggest you stop reading it from there as by that time, it should have caught your attention.\n" +
                "\n" +
                "This anime is light years ahead of all shounen out there. No shounen anime holds a candle to Hunter X Hunter when it comes to being ardent and scrupulous. Amidst all monotonous shounen that have come out on the heels, HxH was able to crank it up a notch. "


        )

    val listData : ArrayList<Review>
        get() {
            val list = arrayListOf<Review>()
            for (position in NamaReviewer.indices){
                val reviews = Review()
                reviews.Namareviewer = NamaReviewer[position]
                reviews.IsiReview = isiReview[position]
                list.add(reviews)
            }
            return list
        }

}